### ISSUE TITLE
Exception while invoking method 'startWallet' TypeError

### ISSUE THREAD

**Issue by jorian** [KomodoPlatform/dicoapp#1]
When using branch `example` and running the dICO-app in the browser with `meteor run`, initially a passphrase is asked. Upon entering a passphrase and submitting it, a loading screen appears with a small loading circle in the center of the screen.

This loading circle is stuck and no other screen appears.

The log states:

```

I20180615-13:42:56.071(2)? [2018-06-15 13:42:56] PM2 log: adding electrum servers
I20180615-13:42:56.425(2)? [2018-06-15 13:42:56] PM2 log: Exception while invoking method 'startWallet' TypeError: Cannot read property 'altserverList' of undefined
I20180615-13:42:56.426(2)?     at MethodInvocation.startWallet (imports/api/marketmaker/methods.js:210:43)
I20180615-13:42:56.431(2)?     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1767:12)
I20180615-13:42:56.432(2)?     at DDP._CurrentMethodInvocation.withValue (packages/ddp-server/livedata_server.js:719:19)
I20180615-13:42:56.433(2)?     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1189:12)
I20180615-13:42:56.433(2)?     at DDPServer._CurrentWriteFence.withValue (packages/ddp-server/livedata_server.js:717:46)
I20180615-13:42:56.434(2)?     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1189:12)
I20180615-13:42:56.434(2)?     at Promise (packages/ddp-server/livedata_server.js:715:46)
I20180615-13:42:56.435(2)?     at new Promise (<anonymous>)
I20180615-13:42:56.436(2)?     at Session.method (packages/ddp-server/livedata_server.js:689:23)
I20180615-13:42:56.437(2)?     at packages/ddp-server/livedata_server.js:559:43
```

Run on MacOS High Sierra 10.13.5
No native coin daemons were used

Followed instructions as defined [here](https://github.com/KomodoPlatform/dicoapp/tree/example#osx--linux)

Used dependency versions:
```
$ node --version
v8.11.3
$ meteor --version
Meteor 1.7.0.3
$ npm --version
5.6.0
```

**Comment by pioryan** [comment]
Still experiencing this issue.
